export const mockTasks = [
  {
    id: 1,
    title: 'Follow up with Acme Corp',
    description: 'Send quarterly business review proposal',
    type: 'todo' as const,
    priority: 'high' as const,
    status: 'pending' as const,
    dueDate: '2025-06-27',
    relatedTo: { type: 'company' as const, id: 1, name: 'Acme Corporation' },
    createdAt: '2025-06-20',
    completed: false,
  },
  {
    id: 2,
    title: 'Prepare presentation for John Smith',
    description: 'Create slide deck for product demo meeting',
    type: 'todo' as const,
    priority: 'high' as const,
    status: 'pending' as const,
    dueDate: '2025-06-28',
    relatedTo: { type: 'contact' as const, id: 1, name: 'John Smith' },
    createdAt: '2025-06-21',
    completed: false,
  },
  {
    id: 3,
    title: 'Tech Trade Show 2025 reminder',
    description: 'Event starts in 2 weeks - finalize booth setup',
    type: 'reminder' as const,
    priority: 'medium' as const,
    status: 'pending' as const,
    dueDate: '2025-07-01',
    relatedTo: { type: 'event' as const, id: 1, name: 'Tech Trade Show 2025' },
    createdAt: '2025-06-15',
    completed: false,
  },
  {
    id: 4,
    title: 'Send contract to Global Manufacturing',
    description: 'Updated pricing and terms as discussed',
    type: 'todo' as const,
    priority: 'medium' as const,
    status: 'completed' as const,
    dueDate: '2025-06-25',
    relatedTo: { type: 'company' as const, id: 2, name: 'Global Manufacturing Inc.' },
    createdAt: '2025-06-20',
    completed: true,
  },
  {
    id: 5,
    title: 'Call Sarah Johnson',
    description: 'Discuss technical requirements for new project',
    type: 'todo' as const,
    priority: 'low' as const,
    status: 'overdue' as const,
    dueDate: '2025-06-24',
    relatedTo: { type: 'contact' as const, id: 2, name: 'Sarah Johnson' },
    createdAt: '2025-06-18',
    completed: false,
  },
  {
    id: 6,
    title: 'Manufacturing Expo registration reminder',
    description: 'Registration deadline is approaching',
    type: 'reminder' as const,
    priority: 'high' as const,
    status: 'pending' as const,
    dueDate: '2025-06-30',
    relatedTo: { type: 'event' as const, id: 2, name: 'Manufacturing Expo' },
    createdAt: '2025-06-22',
    completed: false,
  },
];
