/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppImportIndexRouteImport } from './routes/_app/import/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app/events/$eventId/index'
import { Route as AppContactsAddIndexRouteImport } from './routes/_app/contacts/add/index'
import { Route as AppContactsContactIdIndexRouteImport } from './routes/_app/contacts/$contactId/index'
import { Route as AppCompaniesAddIndexRouteImport } from './routes/_app/companies/add/index'
import { Route as AppCompaniesCompanyIdIndexRouteImport } from './routes/_app/companies/$companyId/index'
import { Route as AppCompaniesCompanyIdEditRouteImport } from './routes/_app/companies/$companyId/edit'
import { Route as AppContactsContactIdEditIndexRouteImport } from './routes/_app/contacts/$contactId/edit/index'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/_app/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImportIndexRoute = AppImportIndexRouteImport.update({
  id: '/_app/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/_app/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/_app/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/_app/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/_app/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsAddIndexRoute = AppContactsAddIndexRouteImport.update({
  id: '/_app/contacts/add/',
  path: '/contacts/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsContactIdIndexRoute =
  AppContactsContactIdIndexRouteImport.update({
    id: '/_app/contacts/$contactId/',
    path: '/contacts/$contactId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompaniesAddIndexRoute = AppCompaniesAddIndexRouteImport.update({
  id: '/_app/companies/add/',
  path: '/companies/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesCompanyIdIndexRoute =
  AppCompaniesCompanyIdIndexRouteImport.update({
    id: '/_app/companies/$companyId/',
    path: '/companies/$companyId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompaniesCompanyIdEditRoute =
  AppCompaniesCompanyIdEditRouteImport.update({
    id: '/_app/companies/$companyId/edit',
    path: '/companies/$companyId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppContactsContactIdEditIndexRoute =
  AppContactsContactIdEditIndexRouteImport.update({
    id: '/_app/contacts/$contactId/edit/',
    path: '/contacts/$contactId/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/import': typeof AppImportIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/companies/$companyId/edit': typeof AppCompaniesCompanyIdEditRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdIndexRoute
  '/companies/add': typeof AppCompaniesAddIndexRoute
  '/contacts/$contactId': typeof AppContactsContactIdIndexRoute
  '/contacts/add': typeof AppContactsAddIndexRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/contacts/$contactId/edit': typeof AppContactsContactIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/import': typeof AppImportIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/companies/$companyId/edit': typeof AppCompaniesCompanyIdEditRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdIndexRoute
  '/companies/add': typeof AppCompaniesAddIndexRoute
  '/contacts/$contactId': typeof AppContactsContactIdIndexRoute
  '/contacts/add': typeof AppContactsAddIndexRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/contacts/$contactId/edit': typeof AppContactsContactIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/': typeof AppIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/import/': typeof AppImportIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/companies/$companyId/edit': typeof AppCompaniesCompanyIdEditRoute
  '/_app/companies/$companyId/': typeof AppCompaniesCompanyIdIndexRoute
  '/_app/companies/add/': typeof AppCompaniesAddIndexRoute
  '/_app/contacts/$contactId/': typeof AppContactsContactIdIndexRoute
  '/_app/contacts/add/': typeof AppContactsAddIndexRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/contacts/$contactId/edit/': typeof AppContactsContactIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/contacts'
    | '/events'
    | '/import'
    | '/tasks'
    | '/companies/$companyId/edit'
    | '/companies/$companyId'
    | '/companies/add'
    | '/contacts/$contactId'
    | '/contacts/add'
    | '/events/$eventId'
    | '/contacts/$contactId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/contacts'
    | '/events'
    | '/import'
    | '/tasks'
    | '/companies/$companyId/edit'
    | '/companies/$companyId'
    | '/companies/add'
    | '/contacts/$contactId'
    | '/contacts/add'
    | '/events/$eventId'
    | '/contacts/$contactId/edit'
  id:
    | '__root__'
    | '/_app/'
    | '/_app/companies/'
    | '/_app/contacts/'
    | '/_app/events/'
    | '/_app/import/'
    | '/_app/tasks/'
    | '/_app/companies/$companyId/edit'
    | '/_app/companies/$companyId/'
    | '/_app/companies/add/'
    | '/_app/contacts/$contactId/'
    | '/_app/contacts/add/'
    | '/_app/events/$eventId/'
    | '/_app/contacts/$contactId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppImportIndexRoute: typeof AppImportIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppCompaniesCompanyIdEditRoute: typeof AppCompaniesCompanyIdEditRoute
  AppCompaniesCompanyIdIndexRoute: typeof AppCompaniesCompanyIdIndexRoute
  AppCompaniesAddIndexRoute: typeof AppCompaniesAddIndexRoute
  AppContactsContactIdIndexRoute: typeof AppContactsContactIdIndexRoute
  AppContactsAddIndexRoute: typeof AppContactsAddIndexRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppContactsContactIdEditIndexRoute: typeof AppContactsContactIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/import/': {
      id: '/_app/import/'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts/add/': {
      id: '/_app/contacts/add/'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof AppContactsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts/$contactId/': {
      id: '/_app/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/add/': {
      id: '/_app/companies/add/'
      path: '/companies/add'
      fullPath: '/companies/add'
      preLoaderRoute: typeof AppCompaniesAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/$companyId/': {
      id: '/_app/companies/$companyId/'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/$companyId/edit': {
      id: '/_app/companies/$companyId/edit'
      path: '/companies/$companyId/edit'
      fullPath: '/companies/$companyId/edit'
      preLoaderRoute: typeof AppCompaniesCompanyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts/$contactId/edit/': {
      id: '/_app/contacts/$contactId/edit/'
      path: '/contacts/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof AppContactsContactIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppImportIndexRoute: AppImportIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppCompaniesCompanyIdEditRoute: AppCompaniesCompanyIdEditRoute,
  AppCompaniesCompanyIdIndexRoute: AppCompaniesCompanyIdIndexRoute,
  AppCompaniesAddIndexRoute: AppCompaniesAddIndexRoute,
  AppContactsContactIdIndexRoute: AppContactsContactIdIndexRoute,
  AppContactsAddIndexRoute: AppContactsAddIndexRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppContactsContactIdEditIndexRoute: AppContactsContactIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
