import type { Company } from './types';

export const mockCompanies: Company[] = [
  {
    id: 1,
    name: 'Grand Hotels Corporation',
    industry: 'Luxury Hotels',
    size: 'Large (1000+ employees)',
    location: 'New York, NY',
    phone: '+1 (555) 123-4567',
    email: 'contact@grandhotels.com',
    website: 'www.grandhotels.com',
    agentsCount: 5,
    eventsCount: 3,
    lastContact: '2025-06-20',
    tags: ['Luxury', 'Chain Hotels', 'Premium Client'],
    description: 'Grand Hotels Corporation is a leading luxury hotel chain with over 250 properties worldwide. They specialize in premium hospitality experiences and corporate events.',
    customFields: [
      { name: 'Annual Revenue', value: '$500M+' },
      { name: 'Primary Contact', value: 'John Smith (VP Sales)' },
      { name: 'Hotel Count', value: '250+ properties' },
      { name: 'Founded', value: '1985' },
      { name: 'Headquarters', value: 'Manhattan, New York' },
      { name: 'CEO', value: 'Michael Johnson' },
    ],
    agents: [
      { id: 1, name: 'Sarah Mitchell', title: 'Senior Sales Agent', lastContact: '2025-06-20' },
      { id: 4, name: 'David Chen', title: 'Junior Sales Agent', lastContact: '2025-06-22' },
    ],
    recentEvents: [
      { id: 1, name: 'International Hotel Investment Summit 2025', date: '2025-07-15', status: 'Upcoming' },
      { id: 3, name: 'Boutique Hotel Summit 2025', date: '2025-09-10', status: 'Completed' },
    ],
  },
  {
    id: 2,
    name: 'Boutique Hospitality Group',
    industry: 'Boutique Hotels',
    size: 'Medium (100-1000 employees)',
    location: 'San Francisco, CA',
    phone: '+1 (555) 987-6543',
    email: 'contact@boutiquegroup.com',
    website: 'www.boutiquegroup.com',
    agentsCount: 8,
    eventsCount: 2,
    lastContact: '2025-06-18',
    tags: ['Boutique', 'Design Hotels', 'Growing Client'],
    description: 'Boutique Hospitality Group operates 45 unique design hotels across the United States, focusing on millennial and Gen Z travelers.',
    customFields: [
      { name: 'Specialization', value: 'Design & Lifestyle Hotels' },
      { name: 'Target Market', value: 'Millennials & Gen Z' },
      { name: 'Properties', value: '45 hotels' },
      { name: 'Founded', value: '2010' },
      { name: 'Expansion Plans', value: '15 new properties by 2026' },
    ],
    agents: [
      { id: 2, name: 'Marcus Rodriguez', title: 'Regional Sales Manager', lastContact: '2025-06-18' },
    ],
    recentEvents: [
      { id: 2, name: 'Resort & Spa Trade Show', date: '2025-08-22', status: 'Planning' },
    ],
  },
  {
    id: 3,
    name: 'Resort & Spa International',
    industry: 'Resort Hotels',
    size: 'Large (1000+ employees)',
    location: 'Miami, FL',
    phone: '+1 (555) 456-7890',
    email: 'sales@resortandspa.com',
    website: 'www.resortandspa.com',
    agentsCount: 3,
    eventsCount: 1,
    lastContact: '2025-06-15',
    tags: ['Resort', 'Spa', 'Vacation'],
    description: 'Resort & Spa International operates all-inclusive luxury resorts in the Caribbean, Mexico, and Hawaii, offering premium spa and wellness experiences.',
    customFields: [
      { name: 'Resort Type', value: 'All-Inclusive & Luxury Spa' },
      { name: 'Locations', value: 'Caribbean, Mexico, Hawaii' },
      { name: 'Average Room Rate', value: '$400+/night' },
      { name: 'Founded', value: '1998' },
      { name: 'Signature Service', value: 'World-class spa treatments' },
    ],
    agents: [
      { id: 3, name: 'Jennifer Park', title: 'Sales Agent', lastContact: '2025-06-15' },
    ],
    recentEvents: [
      { id: 2, name: 'Resort & Spa Trade Show', date: '2025-08-22', status: 'Planning' },
    ],
  },
];
